# Generated by Django 5.0 on 2023-12-11 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tag_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
