# Generated by Django 5.0 on 2023-12-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_task_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tbltag',
        ),
    ]
