name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: "root123"
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: todolist

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        cd todolist/todolist
        pip install -r requirements.txt

    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        DROP USER ''@'localhost';
        FLUSH PRIVILEGES;
        
        
      # GRANT ALL ON sonar.* TO 'sonar'@'localhost' IDENTIFIED BY 'sonar';
        # sudo mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" 
      # ALTER USER 'root'@'localhost' IDENTIFIED BY 'new Password';
       # sudo mysql --user=DB_USER --password=DB_PASSWORD
      
    - name: Create MySQL User and Grant Privileges
      run: |
        mysql -u root -e "CREATE USER 'DB_USER'@'localhost' IDENTIFIED BY 'DB_PASSWORD';"
        mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'DB_USER'@'localhost' WITH GRANT OPTION;"

    # - name: Run CI Tasks with MySQL User
    #   run: |
    #     sudo mysql --user=DB_USER --password=DB_PASSWORD

      # cd todolist/todolist
      # sudo mysql -u$DB_USER -p$DB_PASSWORD
        




    # - name: Run tests
    #   run: |
    #     cd todolist/todolist
    # python manage.py migrate
    #     python manage.py test



        
      # env:
      #   DJANGO_SETTINGS_MODULE: "todolist.settings"
      #   DATABASE_URL: "mysql://$DB_USER:$DB_PASSWORD@localhost:3306/$DB_DATABASE"
            
    # - name: Run Linting
    #   run: |
    #     cd todolist/todolist
    #     python -m flake8

    

