name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: todolist

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        cd todolist/todolist
        pip install -r requirements.txt

    - name: Run Migrations 
      run: |
        cd todolist/todolist
        python manage.py migrate

    - name: Run tests
      run: |
        cd todolist/todolist
        python manage.py test

