name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: mytest_db
      DB_USER: newuser
      DB_PASSWORD: password
   
    steps:
    - name: Set DJANGO_ENV
      run: echo "DJANGO_ENV=ci" >> $GITHUB_ENV
      
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: todolist

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        cd todolist/todolist
        pip install -r requirements.txt

    - name: Start MySQL
      run: |
        sudo service mysql start
        mysql -u root -p'root' -e "show databases;"
        mysql -u root -p'root' -e "SELECT user, host FROM mysql.user;"
        mysql -u root -p'root' -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';"
        mysql -u root -p'root' -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'localhost' WITH GRANT OPTION;"
        mysql -u $DB_USER -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;"
        mysql -u $DB_USER -p$DB_PASSWORD -e "SHOW DATABASES;"

    - name: Run tests
      run: |
        cd todolist/todolist
        python manage.py migrate
        python manage.py test

    - name: Deploy to Production
      run: |
        cd todolist/todolist
        python manage.py migrate
        python manage.py collectstatic 
    
